### PR TITLE
Updated Translation; Added new color and design

### PR DESCRIPTION
**Pull request by fei0316**

### CODE REVIEW

**Comment by Rachel030219** [comment]
`\u0020` is not to be replaced, but just a space between the description and the value appended…

**Comment by fei0316** [comment]
> 
> 
> `\u0020` is not to be replaced, but just a space between the description and the value appended…

It's a variable right? I don't think I removed it but I just moved it around.

**Comment by Rachel030219** [comment]
> > 
> > 
> > `\u0020` is not to be replaced, but just a space between the description and the value appended…
> 
> It's a variable right? I don't think I removed it but I just moved it around.

Not even that. Android removes spaces in the start and end of items in `strings.xml`, and it is used to force display a space.

**Comment by fei0316** [comment]
Ohh I didn't know that. I was trying to add a space before a word in my app also, and was thinking why it didn't work lol
Sorry about that. I will fix that and add that to this PR.

**Comment by fei0316** [comment]
Please check again. I tested it and it works properly now.

**Pull request merged**
